### ISSUE TITLE
Application won't start up

### ISSUE THREAD

**Issue by soufrk** [soufrk/SpringBoot-Examples#1]
Steps to reproduce (in Eclipse)
1. Clone the project
2. Put the key-store file
3. Boot up the application

Observation

- Application fails to start, with stack-trace message 
_The Tomcat connector configured to listen on port 8443 failed to start. The port may already be in use or the connector may be misconfigured._

- Root-cause
```
Caused by: java.lang.IllegalArgumentException: Alias name [1] does not identify a key entry
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:116) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:87) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:225) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1150) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:591) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1018) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	... 14 common frames omitted
Caused by: java.io.IOException: Alias name [1] does not identify a key entry
	at org.apache.tomcat.util.net.jsse.JSSEUtil.getKeyManagers(JSSEUtil.java:229) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:114) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	... 19 common frames omitted
```

**Comment by soufrk** [comment]
Property `server.ssl.keyAlias` in `application.properties` does not have correct alias of the key in the keystore file. Make sure the alias name is correct. In case if you are not sure what the alias name of your key is, you can get a list of all keys in your key-store file, by the command below,
`keytool -list -keystore <your-keystore-file-name>`
