### ISSUE TITLE
Application won't start up - keystore file not found

### ISSUE THREAD

**Issue by soufrk** [soufrk/SpringBoot-Examples#3]
Steps to reproduce (in Eclipse)

1. Clone the project
2. Put key-store file
3. Change alias for key
4. Boot up the application

Observation

 - Application fails to start with stack-trace message
_The Tomcat connector configured to listen on port 8443 failed to start. The port may already be in use or the connector may be misconfigured._
 - Root cause in stack-trace
```
Caused by: java.io.FileNotFoundException: /workspace/SpringBootSecuredRest/Take-2/SecureAppServer/my-key-one.jks (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_181]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_181]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_181]
	at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[na:1.8.0_181]
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90) ~[na:1.8.0_181]
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188) ~[na:1.8.0_181]
	at org.apache.tomcat.util.file.ConfigFileLoader.getInputStream(ConfigFileLoader.java:96) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.SSLUtilBase.getStore(SSLUtilBase.java:132) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.SSLHostConfigCertificate.getCertificateKeystore(SSLHostConfigCertificate.java:204) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.jsse.JSSEUtil.getKeyManagers(JSSEUtil.java:184) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:114) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	... 24 common frames omitted
```

**Comment by soufrk** [comment]
As indicated in the exception, the keystore file is expected in root location of project. If copied there it works. But, this is not a design from deployment perspective. Instead, have a separate directory for keystore under project path.
